services:
  keycloak:
    # https://quay.io/repository/keycloak/keycloak?tab=tags
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: sapporo-keycloak-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=sapporo-admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=sapporo-admin-password
    volumes:
      - ${PWD}/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - 127.0.0.1:8080:8080
    command: ["start-dev", "--import-realm"]
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /realms/sapporo-dev HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && timeout 1 cat <&3 | head -1 | grep -q '200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    networks:
      - sapporo-dev-network
    init: true

networks:
  sapporo-dev-network:
    name: sapporo-dev-network
    external: true
