services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sapporo-service-dev
    container_name: sapporo-service-dev
    environment:
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=1122
      - SAPPORO_DEBUG=True
      - SAPPORO_RUN_DIR=${PWD}/runs
    volumes:
      - .:/app:rw
      - venv:/app/.venv:rw
      - ${PWD}/runs:${PWD}/runs:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:1122:1122
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - sapporo-dev-network
    init: true

volumes:
  venv: {}

networks:
  sapporo-dev-network:
    name: sapporo-dev-network
