# FROM python:3.8.8-buster
FROM python@sha256:d90d328f14fc16e1b2be053ca18a01bb561c543730d5d781b58cc561faabac33

ADD https://download.docker.com/linux/static/stable/x86_64/docker-20.10.3.tgz /tmp/
RUN tar xf /tmp/docker-20.10.3.tgz -C /tmp && \
    mv /tmp/docker/* /usr/bin/ && \
    rmdir /tmp/docker && \
    rm -f /tmp/docker-20.10.3.tgz

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    jq \
    tini && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN python3 -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel && \
    python3 -m pip install --no-cache-dir --progress-bar off -e .[tests]

ENV SAPPORO_HOST 0.0.0.0
ENV SAPPORO_PORT 1122
ENV SAPPORO_DEBUG True

EXPOSE 1122

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
