FROM python:3.10.14-bookworm

WORKDIR /app
COPY . .
RUN python3 -m pip install --no-cache-dir --progress-bar off -U pip && \
    python3 -m pip install --no-cache-dir --progress-bar off -e .[tests]

EXPOSE 1122

ENTRYPOINT []
CMD ["sleep", "infinity"]
