FROM python:3.8.17-bullseye

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    jq \
    tini && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN curl -O https://download.docker.com/linux/static/stable/$(uname -m)/docker-23.0.6.tgz && \
    tar -xzf docker-23.0.6.tgz && \
    mv docker/* /usr/bin/ && \
    rm -rf docker docker-23.0.6.tgz

WORKDIR /app
COPY . .
RUN python3 -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel && \
    python3 -m pip install --no-cache-dir --progress-bar off -e .[tests]

ENV SAPPORO_HOST 0.0.0.0
ENV SAPPORO_PORT 1122
ENV SAPPORO_DEBUG True

EXPOSE 1122

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
