name: Bug Report
description: Report a bug in sapporo-service
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `sapporo ...`
        2. Send request to `POST /runs`
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Version and environment information.
      placeholder: |
        - sapporo-service version: (e.g., 2.1.0)
        - Python version: (e.g., 3.12.0)
        - OS: (e.g., Ubuntu 24.04)
        - Workflow engine: (e.g., cwltool 3.1.x)
        - Docker version: (e.g., 29.2.1)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (stderr.log, stdout.log, etc.).
      render: shell
