swagger: "2.0"
info:
  title: SAPPORO-service REST-API Definition
  description: SAPPORO-service REST-API Specification Sheet
  version: 1.0.0
host: localhost:1122
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /service-info:
    get:
      summary: Get information about Workflow Execution Service.
      description: |-
        May include information about available workflow engines, the WES API versions supported, and information about general service availability.
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/ServiceInfo"
        "500":
          description: An unexpected error occurred.
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - WorkflowExecutionService
  /runs:
    get:
      summary: Get the list of runs.
      description: |-
        Get a list of workflow runs that the service has executed or is executing.
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/RunListResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: An unexpected error occurred.
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - WorkflowExecutionService
    post:
      summary: Run a workflow.
      description: >-
        This endpoint creates a new workflow run and
        returns a `run_id` and `status` to monitor its progress.
      responses:
        "201":
          description: ""
          schema:
            $ref: "#/definitions/RunResponse"
        "400":
          description: ""
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: An unexpected error occurred.
          schema:
            $ref: "#/definitions/ErrorResponse"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: workflow_name
          type: string
        - in: formData
          name: execution_engine_name
          type: string
        - in: formData
          name: workflow_parameters
          type: file
          format: "text/plane"
        - in: formData
          name: upload_info
          type: file
          format: "text/plane"
      tags:
        - WorkflowExecutionService
  /runs/{run_id}:
    get:
      summary: Get detailed info about a workflow run.
      description: >-
        This endpoint provides detailed information about a given workflow run.
        The returned result has information about the outputs produced by this workflow
        (if available), a log object which allows the stderr and stdout to be retrieved,
        a log array so stderr/stdout for individual tasks can be retrieved,
        and the overall status of the workflow run (e.g. RUNNING, see the Status section).
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/RunLog"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: An unexpected error occurred.
          schema:
            $ref: "#/definitions/ErrorResponse"
      parameters:
        - name: run_id
          in: path
          required: true
          type: string
      tags:
        - WorkflowExecutionService
  /runs/{run_id}/cancel:
    post:
      summary: Cancel a running workflow.
      responses:
        "201":
          description: ""
          schema:
            $ref: "#/definitions/RunResponse"
        "400":
          description: ""
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: An unexpected error occurred.
          schema:
            $ref: "#/definitions/ErrorResponse"
      parameters:
        - name: run_id
          in: path
          required: true
          type: string
      tags:
        - WorkflowExecutionService
  /workflows:
    get:
      summary: Get workflow list.
      description: >-
        Get workflow list.
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/WorkflowList"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: An unexpected error occurred.
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - WorkflowExecutionService
definitions:
  ServiceInfo:
    type: object
    properties:
      supported_wes_versions:
        type: array
        items:
          type: string
          example: v1.0.0
        description: The version(s) of the WES schema supported by this service
      workflow_engines:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              example: cwltool
            version:
              type: string
              example: 1.0.20181201184214
            workflow_types:
              type: array
              items:
                $ref: "#/definitions/WorkflowType"
              description: >-
                A map with keys as the workflow format type name (currently only CWL and WDL are used
                although a service may support others) and value is a workflow_type_version object which
                simply contains an array of one or more version strings
        description: >-
          The engine(s) used by this WES service, key is engine name (e.g. Cromwell) and value is version
      upload_protocols:
        type: array
        items:
          type: object
          properties:
            protocol_name:
              type: string
              example: s3
            parameters:
              type: array
              items:
                type: string
                example:
                  [endpoint, access_key, secret_access_key, bucket, upload_dir]
      auth_instructions_url:
        type: string
        example: https://dummy_auth_instructions_url/
        description: >-
          A web page URL with human-readable instructions on how to get an
          authorization token for use with a specific WES endpoint.
      contact_info_url:
        type: string
        example: https://dummy_contact_info_url/
        description: >-
          An email address URL (mailto:) or web page URL with contact information
          for the operator of a specific WES endpoint. Users of the
          endpoint should use this to report problems or security
          vulnerabilities.
    description: >-
      A message containing useful information about the running service, including supported versions and
      default settings.
  RunListResponse:
    type: array
    items:
      $ref: "#/definitions/RunResponse"
  RunResponse:
    type: object
    properties:
      run_id:
        type: string
        example: 158c32a8-6baf-4b34-8fdb-8ec5b9c90db7
      status:
        type: string
        example: COMPLETE
        description: The status of the run e.g. (PENDING, RUNNING, FINISH, CANCELED, COMPLETE, SYSTEM_ERROR, EXECUTOR_ERROR)
    description: >-
      A run information that the service has executed or is executing.
  RunLog:
    type: object
    properties:
      run_id:
        type: string
        description: workflow run ID
        example: 158c32a8-6baf-4b34-8fdb-8ec5b9c90db7
      workflow_name:
        type: string
        example: bwa_mapping_pe
      workflow_version:
        type: string
        example: 0c33f861553629b1e6fb4161686ab47670c9ed97
        description: Such as a GitHub commit id.
      workflow_location:
        type: string
        example: "https://github.com/suecharo/SAPPORO/raw/develop/SAPPORO-service/test_workflow/bwa_mapping_pe.cwl"
      workflow_content:
        type: string
        description: Workflow file's content.
      workflow_parameters_template_location:
        type: string
        example: "https://github.com/suecharo/SAPPORO/raw/develop/SAPPORO-service/test_workflow/bwa_mapping_pe_run_template.yml"
      workflow_parameters:
        type: string
        description: Workflow parameters file's content.
      language_type:
        type: string
        example: CWL
      language_version:
        type: string
        example: v1.0
      execution_engine_name:
        type: string
        example: cwltool
      execution_engine_version:
        type: string
        example: 1.0.2018121184214
      statue:
        type: string
        example: COMPLETE
        description: The statue of the run e.g. (PENDING, RUNNING, FINISH, CANCELED, COMPLETE, SYSTEM_ERROR, EXECUTOR_ERROR)
      stdout:
        type: string
        description: Workflow engine's stdout
      stderr:
        type: string
        description: Workflow engine's stderr
      upload_url:
        type: string
        example: "s3://bucket-name/upload_dir/"
      start_time:
        type: string
        example: "2019-01-01 00:00:00"
      end_time:
        type: string
        example: "2019-01-01 00:09:00"
  WorkflowType:
    type: object
    properties:
      language_type:
        type: string
        example: CWL
      language_version:
        type: string
        example: v1.0
    description: Available workflow types supported by a given instance of the service.
  Workflow:
    type: object
    properties:
      workflow_name:
        type: string
        example: bwa_mapping_pe
      workflow_version:
        type: string
        example: 0c33f861553629b1e6fb4161686ab47670c9ed97
        description: Such as a GitHub commit id.
      workflow_location:
        type: string
        example: "https://github.com/suecharo/SAPPORO/raw/develop/SAPPORO-service/test_workflow/bwa_mapping_pe.cwl"
      workflow_content:
        type: string
        description: Workflow file's content.
      workflow_parameters_template_location:
        type: string
        example: "https://github.com/suecharo/SAPPORO/raw/develop/SAPPORO-service/test_workflow/bwa_mapping_pe_run_template.yml"
      workflow_parameters_template:
        type: string
        description: Workflow template file's content.
      language_type:
        type: string
        example: CWL
      language_version:
        type: string
        example: v1.0
  WorkflowList:
    type: object
    properties:
      workflows:
        type: array
        items:
          $ref: "#/definitions/Workflow"
  ErrorResponse:
    description: >-
      An object that can optionally include information about the error.
    type: object
    properties:
      msg:
        type: string
        description: A detailed error message.
      status_code:
        type: integer
        description: The integer representing the HTTP status code (e.g. 200, 404).
